### ISSUE TITLE
does this plugin support elgg as an LDAP source / consumer or both?

### ISSUE THREAD

**Issue by propertunist** [Elgg/ldap_auth#4]
i am new to LDAP (beyond using it on my email server) and i need to connect elgg to a chat server using something like LDAP. i am wondering whether this plugin would provide an interface (and directory) that the chat server can use to sync against.. or whether this plugin is intended to allow elgg to sync to another system... or maybe the plugin support both?
i'm running the plugin (juho's fork) in elgg 2.1.2 and looking at the admin panel, but since there is no readme, it is not clear to me what the situation is.

**Comment by mrclay** [comment]
It just consumes an LDAP service to check credentials and get an email for the user. Have you posted to community what you're trying to do?

**Comment by propertunist** [comment]
@mrclay yes i opened a thread on this and ismayil pointed me to this ldap plugin.. that was the only reply i got. the community has been pretty quiet lately. see: https://elgg.org/discussion/view/2512297/oauth-for-elgg-2x-or-other-forms-of-authentication-that-can-sync-elgg-with-a-chat-application
